#Canvas
SEEN_CANVAS_WIDTH = 1500
SEEN_CANVAS_HEIGHT = 1500

SEEN_CANVAS_WIDTH_HALF = int(SEEN_CANVAS_WIDTH/2)
SEEN_CANVAS_HEIGHT_HALF = int(SEEN_CANVAS_HEIGHT/2)

WHOLE_CANVAS_WIDTH = int(SEEN_CANVAS_WIDTH*1.2)
WHOLE_CANVAS_HEIGHT = int(SEEN_CANVAS_HEIGHT*1.2)

SEEN_CANVAS_X_MIN = int(SEEN_CANVAS_WIDTH * 0.1)
SEEN_CANVAS_X_MAX = int(SEEN_CANVAS_WIDTH * 1.1)

SEEN_CANVAS_Y_MIN = int(SEEN_CANVAS_HEIGHT * 0.1)
SEEN_CANVAS_Y_MAX = int(SEEN_CANVAS_HEIGHT * 1.1)

FPS = 60

PERK_SPAWN_PROB_PER_SECOND = 0.5
PERK_SPAWN_PROB_PER_FRAME = PERK_SPAWN_PROB_PER_SECOND/FPS

ASTEROID_START_NUMBER = 4
INITIAL_ASTEROID_SPAWN_PROB_PER_SECOND = 0.04
INITIAL_ASTEROID_SPAWN_PROB_PER_FRAME = INITIAL_ASTEROID_SPAWN_PROB_PER_SECOND/FPS
INCREASE_PER_MINUTE_OF_ASTEROID_SPAWN_PROB_PER_FRAME = 0.1
        

